[project]
name = "django-ecommerce1"
version = "0.2.0"
description = "A typical django framework for ecommerce application."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2",
    "django-localflavor==5.0",
    "pillow>=12",
    "stripe>=14",
]
